### ISSUE TITLE
how to reference external css file

### ISSUE THREAD

**Issue by murunwas** [selectpdf/selectpdf-free-html-to-pdf-converter#1]
how to reference css file (e.g bootstrap file) on the code if i want to export specific "div element" or element by id.

**Comment by selectpdf** [comment]
You need to add the css reference in front of your DIV element html:

```
<link rel='stylesheet' href='//path/to/css.css' type='text/css' media='all' />
```

**Comment by sarmaghanahmed** [comment]
Didn't get it @selectpdf ... Can you please explain a little or share a sample...?
