### ISSUE TITLE
Conversion failure. Could not find Chromium binaries (trying to load from *[Solution]\[Project]\Chromium\).

### ISSUE THREAD

**Issue by hasangursoy** [selectpdf/selectpdf-free-html-to-pdf-converter#12]
I'm trying to use Blink as rendering engine but it fails. Installed Select.HtmlToPdf.NetCore.Blink and using .net v4.8.

I have a single file "Select.Html.dep" inside bin folder. Running with iisexpress.

    // instantiate a html to pdf converter object
    var converter = new HtmlToPdf()
    {
        Options = {
            RenderingEngine = RenderingEngine.Blink,
            PdfPageSize = PdfPageSize.A4,
            PdfPageOrientation = PdfPageOrientation.Portrait,
            MarginTop = 20,
            MarginRight = 20,
            MarginBottom = 20,
            MarginLeft = 20,
    
            DisplayFooter = true
        }
    };
    
    // create a new pdf document converting an url
	var doc = converter.ConvertUrl(url);

	// save pdf document
	byte[] response = doc.Save();

	// close pdf document
	doc.Close();

**Comment by selectpdf** [comment]
See where the package manager installed the package and either copy the Chromium folder to your bin folder or point to that folder using BlinkEnginePath property of converter.Options.

**Comment by hasangursoy** [comment]
I thought this was done automatically. Thank you.
