### ISSUE TITLE
Use converter in AWS Lambda function 

### ISSUE THREAD

**Issue by pan1982** [selectpdf/selectpdf-free-html-to-pdf-converter#16]
Hello, i need help with aws lambda. When i test my function i receive an error
`{"@t":"2021-06-11T13:11:33.1130769Z","@mt":"**Conversion failure. Unable to load shared library 'kernel32.dll' or one of its dependencies**. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory","@l":"Error","@x":"System.Exception: Conversion failure. Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: **libkernel32.dll: cannot open shared object file: No such file or directory**\n   at SelectPdf.HtmlToImage.ᜀ(String A_0, String A_1, String A_2, ឭ[]& A_3, ជ& A_4, String& A_5)\n   at SelectPdf.HtmlToPdf.ᜂ(String A_0, String A_1, String A_2, String A_3, Boolean A_4)\n   at SelectPdf.HtmlToPdf.ConvertHtmlString(String htmlString)...}`

I had same error with **'libgdiplus'**, managed by adding library to lambda layer, but i can't find libkernel32.dll
Can you help with this? Maybe you have better solution
Thank you

**Comment by selectpdf** [comment]
I am afraid SelectPdf only works on Windows systems.
