### ISSUE TITLE
Unable to load shared library 'kernel32.dll' on Linux

### ISSUE THREAD

**Issue by StefanoP73** [selectpdf/selectpdf-free-html-to-pdf-converter#2]
We use asp.net core with Select.HtmlToPdf.NetCore and tested a simple code to convert a url in pdf.
In windows all works fine, but in linux we recieved the error:
Conversion failure. Unable to load shared library 'kernel32.dll' or one of its dependencies
at SelectPdf.HtmlToImage

I thought that the .NETStandard reference makes the code's platform independent.
Are you using some internal reference to windows dll?

**Comment by selectpdf** [comment]
Hi,

Sorry, our tool only works on Windows.

Regards,
SelectPdf Support 
http://selectpdf.com

**Comment by davidparker** [comment]
then dont do a multi platform version on dotnet core then

**Comment by ghost** [comment]
Why even bother to create a netcore version if it only works on Windows :D

**Comment by maidmariandev** [comment]
Literally a big waste of time, thanks.

**Comment by Denny966** [comment]
![this is fine](https://user-images.githubusercontent.com/12098006/79335684-b75a8580-7f22-11ea-87b6-ecd33f5b51e7.gif)

**Comment by selectpdf** [comment]
Hi,

 

I am afraid that our library currently work on Windows only.

 

 

Regards,

SelectPdf Support

 <https://selectpdf.com> https://selectpdf.com

**Comment by GeradeDev** [comment]
@selectpdf 
Why do you still have up on your website:
https://ironpdf.com/docs/questions/docker-linux/

Remove it if it's not the case.

**Comment by selectpdf** [comment]
Hi,

That is not our website.

Regards,
SelectPdf Support 
http://selectpdf.com

**Comment by nellstephanj** [comment]
Any plans on adding support for Linux?

**Comment by ognjenkurtic** [comment]
![image](https://user-images.githubusercontent.com/23699661/104916081-ddb9bf80-5991-11eb-9740-bb2807f05663.png)

Could you please do yourself a favor and add a big warning somewhere here stating that this is a net core library which is actually not cross-platform?

**Comment by selectpdf** [comment]
[https://selectpdf.com/html-to-pdf/docs/html/Index.htm](https://selectpdf.com/html-to-pdf/docs/html/Index.htm)

Note: SelectPdf currently works only on Windows systems. There is no support for Linux, Xamarin or other platforms.

**Comment by ognjenkurtic** [comment]
I dont think you got my point. People are still managing to miss that (as evident by this open issue) because everyone defaults to cross-platform as soon as Net Core is mentioned. We had two people on the team missing that information.

**Comment by sanderj6** [comment]
Have you found any alternatives that work on all platforms, @ognjenkurtic ?

**Comment by ognjenkurtic** [comment]
> Have you found any alternatives that work on all platforms, @ognjenkurtic ?

We explored this one - https://github.com/HakanL/WkHtmlToPdf-DotNet. We get correct PDF outputs, should be cross-platform but there is an open issue for Linux support: https://github.com/HakanL/WkHtmlToPdf-DotNet/issues/28. We are temporarily working with ITextSharp.

**Comment by ntimmerman** [comment]
To any vendor listening, when you run apps on Azure, the savings by switching from Windows App Services to Linux is substantial enough to justify buying licenses for 3rd party components.

**Comment by Qasim-Aziz** [comment]
i am devops and struggling from 1 week over this issue then i found this link . i was running dotnet app in container every thing seems working apart form selectpdf.

**Comment by Vnuuk** [comment]
Ugh.. Ugh... So I spent ~1 day trying to get it working. Now I see this :(

**Comment by josephadah** [comment]
This is so annoying and frustrating seeing this after several hours of debugging....

How will you create a dotnetcore package which is not cross platform. 
Why do we have netcore in the first place. 
Everybody is going the containerization route and will definitely use Linux.

You guys never care to put a warning on your site like:
WARNING: SELECTPDF DOES NOT WORK ON LINUX.

**Comment by Ali-ite** [comment]
I have same issue I try with ironpdf I have same problem

**Comment by BC89** [comment]
SelectPDF do you plan on supporting Linux?
