### ISSUE TITLE
Conversion error: Navigation timeout.

### ISSUE THREAD

**Issue by barbarmawad** [selectpdf/selectpdf-free-html-to-pdf-converter#20]
I'm getting this error.
System.Exception: Conversion error: Navigation timeout.
   at SelectPdf.HtmlToImage.ᜀ(String A_0, String A_1, String A_2, ជ& A_3, String& A_4)
   at SelectPdf.HtmlToPdf.ᜁ(String A_0, String A_1, String A_2, String A_3, Boolean A_4)
   at SelectPdf.HtmlToPdf.ConvertHtmlString(String htmlString).
   
   I'm using Azure Appservice, it's not working there but locally it is.
   Please note that I checked the troubleshooting section on your website and did all the changes and it's still not working on Azure.
   
   Here is my code:
   
              GlobalProperties.EnableRestrictedRenderingEngine = true;

            SelectPdf.HtmlToPdf converter = new SelectPdf.HtmlToPdf(600);
            converter.Options.MaxPageLoadTime = 120;
            SelectPdf.PdfDocument doc = converter.ConvertHtmlString(builder.ToString());

            var bytes = doc.Save();
            
            
 Also note that I have the latest version and Select.Html.dep file has full access on the server

**Comment by selectpdf** [comment]
From:
https://selectpdf.com/docs/SelectPdf-Microsoft-Azure.htm

SelectPdf (v18.3) or above works on Azure Web Apps, on Windows, **starting with the Basic plan** (does not work with Free/Shared plans).
