### ISSUE TITLE
SVG and External images are not showing

### ISSUE THREAD

**Issue by nikhilkcc** [selectpdf/selectpdf-free-html-to-pdf-converter#21]
Hi Team, 

We are using **select.htmltopdf** for creating PDF document from a webpage URL. Its working fine except svg images and external URLs. Could you please help to solve the issue?
URL: https://www.kcprofessional.com/en-us/products/dispensers/paper-towel-dispensers/hard-roll/scott-pro-manual-hard-roll-towel-dispenser/29736  

https://www.screencast.com/t/Y45zhoWHg  Please find the download PDF button here. 

Thanks,
Nikhil

**Comment by selectpdf** [comment]
Your download pdf button generates a PDF that does not use our tool.

**Comment by nikhilkcc** [comment]
ok.. thanks
