### ISSUE TITLE
SelectHtmlToPDF Version 21.2 on Azure Web App returns status code 400 with no meaningful stack trace or messages

### ISSUE THREAD

**Issue by elitz123** [selectpdf/selectpdf-free-html-to-pdf-converter#24]
Recently purchased a single license for SelectPDF. Works fine locally in my dev environment called from my .net core 3.1 webapi app.  INstalled my web api app on azure (configured with a B=Basic app plan) . Everything else works ok but the calls to selectpdf fail with a 400 status code and no logging or stack trace that i can find looking through the azure logs. I've read the documentation and limitations using selectpdftlhtml on azure, but i think i'm working within those constraints. Any thoughts on how to trace down the root cause of the 400 status code ? Any logging that selectpdftohtml emits that i can look into ? 

Additional Note: 
I also added these 2 config lines to Configure method in  startup.cs just in case...although from what i read , these are default settings out of the box.
SelectPdf.GlobalProperties.EnableRestrictedRenderingEngine = true;
SelectPdf.GlobalProperties.EnableFallbackToRestrictedRenderingEngine = true;

thanks

**Comment by selectpdf** [comment]
First of all you need to try to get an actual error from SelectPdf library.

Error 400 is a Bad Request error. Not sure what that means exactly on Azure, but for sure it has nothing to do with SelectPdf.

**Comment by elitz123** [comment]
Thanks. Figured out is was in fact an uncaught  exception in my own code wrapped around the calls to selectpdf. closing issue.
