### ISSUE TITLE
SVG images are not rendering

### ISSUE THREAD

**Issue by mlipovaca** [selectpdf/selectpdf-free-html-to-pdf-converter#28]
Is it possible to render svg images from HTML to PDF side ?

@selectpdf

**Comment by selectpdf** [comment]
It should be possible. Please provide test html/svg and code.

**Comment by mlipovaca** [comment]
> It should be possible. Please provide test html/svg and code.

We're loading image from external URL (example: [https://chicks-payment-methods.s3.amazonaws.com/99fab186-0e5e-4cad-8508-d9f8bb0b740d](https://chicks-payment-methods.s3.amazonaws.com/99fab186-0e5e-4cad-8508-d9f8bb0b740d))

If you try also on demo code with `<img src="https://chicks-payment-methods.s3.amazonaws.com/99fab186-0e5e-4cad-8508-d9f8bb0b740d" width="20" height="20">` it doesn't work either w/ rendering.

**Comment by selectpdf** [comment]
It works if you use Blink as rendering engine.

**Comment by mlipovaca** [comment]
We're using library `Select.HtmlToPdf.NetCore` v21.2.0

```csharp
var htmlPath = Path.Combine(_basePath, @"Templates/Receipt.html");
var htmlSource = await File.ReadAllTextAsync(htmlPath);

var partialPath = Path.Combine(_basePath, @"Templates/OrderItem.html");
var partialSource = await File.ReadAllTextAsync(partialPath);

Handlebars.RegisterTemplate("orderItem", partialSource);

var template = Handlebars.Compile(htmlSource);

var compiledHtml = template(order);
compiledHtml = compiledHtml.Replace("__styles__/", Path.Combine(_basePath, _stylesPath));
compiledHtml = compiledHtml.Replace("__images__/", Path.Combine(_basePath, _imagePath));
var doc = _converter.ConvertHtmlString(compiledHtml, _basePath);

return doc.Save();
```

Inside Receipt.html

```html
<img class="payment-method-icon mb-1 me-2" src="https://chicks-payment-methods.s3.amazonaws.com/{{PaymentMethod.ImagePath}}" alt="{{PaymentMethod.Name}} Image" loading="lazy">
```

---

**EDIT:** Got it working ! Needed to install library `SelectPdf.HtmlToPdf.NetCore.Blink` & add `converter.Options.RenderingEngine = RenderingEngine.Blink` . Big thanks SelectPdf ❤️
