### ISSUE TITLE
How to display image in pdf (html-to-pdf conversion)

### ISSUE THREAD

**Issue by mspace** [selectpdf/selectpdf-free-html-to-pdf-converter#3]
I have next html page (not completed yet, here only the important parts for demonstration):

    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>    
      #wrapper {
       height: 841px;
       width: 595px;
      }

      #bg {
        position: absolute; 
        top: 0; 
        left: 0; 
        height: 841px;
        width: 595px;
      }
    </style>
    </head>
    <body>
      <div id="wrapper">
        <img src="bg.png" id="bg" />
      </div>
    </body>
    </html>

Where the page is saved, also file bg.png is saved. The pdf report doesn't show up with image. I'm using next code to generate pdf.

    public ActionResult Test()
    {
      string content = System.IO.File.ReadAllText(@"D:\workspace\index.html");

      HtmlToPdf converter = new HtmlToPdf();

      converter.Options.AutoFitHeight = HtmlToPdfPageFitMode.NoAdjustment;
      converter.Options.AutoFitWidth = HtmlToPdfPageFitMode.AutoFit;
      converter.Options.PdfPageSize = PdfPageSize.A4;

      // create a new pdf document converting an url
      PdfDocument doc = converter.ConvertHtmlString(content);
      byte[] bytes = doc.Save();
      doc.Close();

      FileResult fileResult = new FileStreamResult(new System.IO.MemoryStream(bytes), "application/pdf")
      {
        FileDownloadName = "export.pdf"
      };

      return fileResult;
    }

Is there something I have missed

**Comment by selectpdf** [comment]
You need to provide the base url for your image, because the converter does not know where bg.png is located.

`PdfDocument doc = converter.ConvertHtmlString(content, baseUrl);`

**Comment by mspace** [comment]
There are two solutions:

First one is the one you mentioned, so the change is:

    {
      string appDirReport = "App_data\\index.html";
      string reportFileName = AppDomain.CurrentDomain.BaseDirectory + appDirReport;
      var baseUrl = Request.Url.GetLeftPart(UriPartial.Authority);

      ....

      // create a new pdf document converting an url
      PdfDocument doc = converter.ConvertHtmlString(content, baseUrl);
 
But the page must be served on http server (localhost, whatever)

The second solution is to embed the image as base64 encoded string and it also works - the image is shown in pdf.

Thank you.

**Comment by selectpdf** [comment]
Correct.
