### ISSUE TITLE
ConvertHtmlString is not working on linux

### ISSUE THREAD

**Issue by kirticism** [selectpdf/selectpdf-free-html-to-pdf-converter#30]
Hi,

The following line of code _**var pdfDocument = converter.ConvertHtmlString(htmlContent);**_ does not work on Linux (ubuntu), although it functions smoothly on Windows. Additionally I have implemented this on .net core 6

I have also tried installing the necessary dependency packages on Linux, Despite installing these packages, the issue persists:

sudo apt-get install -y libgdiplus
sudo apt-get install -y libc6-dev
sudo apt-get install -y libx11-dev
sudo apt-get install -y libfontconfig1
sudo apt-get install -y libfreetype6
sudo apt-get install -y libxrender1
sudo apt-get install -y libxext6
sudo apt-get install -y mono-complete

**Comment by selectpdf** [comment]
Hi,

I am afraid that our tool only works on Windows.

Thanks,

**Comment by kirticism** [comment]
> Hi,
> 
> I am afraid that our tool only works on Windows.
> 
> Thanks,

Are there any plans for making it compatible on Linux?
