### ISSUE TITLE
Hide header on last page

### ISSUE THREAD

**Issue by lesley-w** [selectpdf/selectpdf-free-html-to-pdf-converter#4]
We are generating PDFs of a document that could be 2, 3 or 4 pages long, and we want to hide the header on the last page. 

Adding a blank custom header to the last page prevents that standard header from being displayed, however, even with the custom header height set to 1px, the PDF has blank space equal to the height of the standard header.

How can we configure the last page so that there is no header and no blank header space at the top of the page?

**Comment by selectpdf** [comment]
Hi,

 

I am afraid that it’s not possible to remove the header on the last page completely. You can modify it, but the height will remain.

 

 

Regards,

Select.Pdf Support

https://selectpdf.com
