### ISSUE TITLE
Select PDF With Bootstrap CSS

### ISSUE THREAD

**Issue by kdpraveen** [selectpdf/selectpdf-free-html-to-pdf-converter#5]
I have html page with Bootstrap styling, when i convert html to PDF using Select PDF, The output od PDF is omitting the Bootstrap CSS Style and the page is not fully shown in PDF. any suggestions...

**Comment by selectpdf** [comment]
Hi,

 

Please provide a test url and the generated pdf.

 

 

Regards,

Select.Pdf Support

https://selectpdf.com

**Comment by gazimetal** [comment]
Hello,

What should we do to solve this problem? Have you reached any solution? While creating PDF, it creates pdf by skipping css.

Since the dimensions in the created PDF are not css, they are nested.

https://bit.ly/30voJT0

**Comment by selectpdf** [comment]
Please provide a test url and the generated pdf.
